- name: facts using
  hosts: webserver
  become: true
  gather_facts: yes 
  tasks:
       - name: install apache2
         apt:
           name: apache2
           state: absent
         when:  ansible_os_family == "Debian"
